//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaElectric_DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlphaElectricEntitiesDB : DbContext
    {
        public AlphaElectricEntitiesDB()
            : base("name=AlphaElectricEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Designation> Designations { get; set; }
        internal DbSet<Product> Products { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<PanelShellGradeProtection> PanelShellGradeProtections { get; set; }
        public DbSet<SizeType> SizeTypes { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<Certification> Certifications { get; set; }
        public DbSet<Make> Makes { get; set; }
        public DbSet<PaType> PaTypes { get; set; }
        public DbSet<CustomerOrder> CustomerOrders { get; set; }
        public DbSet<Product_CustomerOrderBT> Product_CustomerOrderBT { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public DbSet<Product_PurchaseOrderBT> Product_PurchaseOrderBT { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Panel_ProjectBT> Panel_ProjectBT { get; set; }
        public DbSet<EmployeeStatus> EmployeeStatus { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
    }
}
