//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaElectric_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_ProjectBT
    {
        public int Quantity { get; set; }
        public int PanelID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual Project Project { get; set; }
    }
}
