//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaElectric_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_CustomerOrderBT = new HashSet<Product_CustomerOrderBT>();
            this.Product_PurchaseOrderBT = new HashSet<Product_PurchaseOrderBT>();
        }
    
        public int ID { get; set; }
        public string SerialNo { get; set; }
        public string Name { get; set; }
        public int MakeID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Make Make { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_CustomerOrderBT> Product_CustomerOrderBT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_PurchaseOrderBT> Product_PurchaseOrderBT { get; set; }
    }
}
