//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaElectric_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Panel_ProjectBT = new HashSet<Panel_ProjectBT>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DeliveyDate { get; set; }
        public int CustomerOrderID { get; set; }
    
        public virtual ICollection<Panel_ProjectBT> Panel_ProjectBT { get; set; }
        public virtual CustomerOrder CustomerOrder { get; set; }
    }
}
