//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaElectric_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.Product_PurchaseOrderBT = new HashSet<Product_PurchaseOrderBT>();
        }
    
        public int ID { get; set; }
        public System.DateTime PODate { get; set; }
        public int ContactID { get; set; }
        public int OrderStatusID { get; set; }
        public int EmployeeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_PurchaseOrderBT> Product_PurchaseOrderBT { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
